events {}

http {

    upstream insurance_backend {

        server fastapi1:8000;
 
    }

    server {

        listen 80;

        location / {

            proxy_pass http://insurance_backend;
  
        }

    }

}
